services:
  bot:
    build: .
    container_name: landau-moder
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.toml:/app/config.toml:ro
      - ./l10n:/app/l10n:ro
      - bot_data:/app/data
    environment:
      TZ: ${TZ}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_OWNERS: ${BOT_OWNERS}
      MONGODB_USERNAME: ${MONGODB_USERNAME}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_CLUSTER_URL: ${MONGODB_CLUSTER_URL}
      MONGODB_APP_NAME: ${MONGODB_APP_NAME}
      LOGS_SHOW_DATETIME: ${SHOW_DATETIME}
      LOGS_DATETIME_FORMAT: ${DATETIME_FORMAT}
      LOGS_SHOW_DEBUG_LOGS: ${SHOW_DEBUG_LOGS}
      LOGS_TIME_IN_UTC: ${TIME_IN_UTC}
      LOGS_USE_COLORS_IN_CONSOLE: ${USE_COLORS_IN_CONSOLE}
      LOCALIZATION_DEFAULT_LOCALE: ${LOCALE}
      LOCALIZATION_FALLBACK_LOCALE: ${FALLBACK_LOCALE}
      LOCALIZATION_LOCALES_PATH: ${LOCALES_PATH}
      THROTTLING_ENABLED: ${ENABLED}
      THROTTLING_RATE_LIMIT: ${RATE_LIMIT}
      THROTTLING_MAX_USERS: ${MAX_USERS}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - internals

  redis:
    image: redis:latest
    container_name: redis-landau-moder
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    networks:
      - internals
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "--no-auth-warning", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: landau-moder-redis-commander
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HTTP_USER=admin
      - HTTP_PASSWORD=${ME_ADMIN_PASSWORD}
    networks:
      - internals
    ports:
      - "8082:8081"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  bot_data:
  redis_data:

networks:
  internals:
